# Generated by Django 3.2.2 on 2021-05-19 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_alter_ticket_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='image',
            field=models.ImageField(blank=True, null=True, storage='images', upload_to=''),
        ),
    ]
